package com.drive.backend.grpc.service;

import io.quarkus.example.FileService;
import io.quarkus.grpc.GrpcService;
import io.smallrye.common.annotation.RunOnVirtualThread;

@GrpcService
public class FileInfoService implements FileService {
    /**
     * This service implements the FileService interface generated by the Mutiny Grpc generator.
     * It provides an implementation for the uploadFile method.
     */
    @RunOnVirtualThread
    @Override
    public io.smallrye.mutiny.Uni<io.quarkus.example.FileUploadResponse> uploadFile(io.quarkus.example.FileUploadRequest request) {
        // Implement the file upload logic here
        // For now, just return a dummy response
        io.quarkus.example.FileUploadResponse response = io.quarkus.example.FileUploadResponse.newBuilder()
                .setSuccess(true)
                .setMessage("File uploaded successfully")
                .build();
        return io.smallrye.mutiny.Uni.createFrom().item(response);
    }

    /**
     * Implementation of the deleteFile method from the FileService interface.
     */
    @RunOnVirtualThread
    @Override
    public io.smallrye.mutiny.Uni<io.quarkus.example.FileOperationResponse> deleteFile(io.quarkus.example.FileDeleteRequest request) {
        // Implement the file deletion logic here
        // For now, just return a dummy response
        io.quarkus.example.FileOperationResponse response = io.quarkus.example.FileOperationResponse.newBuilder()
                .setSuccess(true)
                .setMessage("File deleted successfully: " + request.getFilename())
                .build();
        return io.smallrye.mutiny.Uni.createFrom().item(response);
    }

    /**
     * Implementation of the renameFile method from the FileService interface.
     */
    @RunOnVirtualThread
    @Override
    public io.smallrye.mutiny.Uni<io.quarkus.example.FileOperationResponse> renameFile(io.quarkus.example.FileRenameRequest request) {
        // Implement the file renaming logic here
        // For now, just return a dummy response
        io.quarkus.example.FileOperationResponse response = io.quarkus.example.FileOperationResponse.newBuilder()
                .setSuccess(true)
                .setMessage("File renamed successfully from: " + request.getOldFilename() + " to: " + request.getNewFilename())
                .build();
        return io.smallrye.mutiny.Uni.createFrom().item(response);
    }
}
