services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    ports:
      - "9010:9000"  # S3 API port
      - "9011:9001"  # Console port
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:9000/rustfs/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  rustfs_data:
