package com.drive.backend.grpc.service;

import com.drive.backend.grpc.dto.FileInfoDto;
import io.quarkus.example.FileInfo;
import io.quarkus.example.FileService;
import io.quarkus.example.ListUserFilesRequest;
import io.quarkus.example.ListUserFilesResponse;
import io.quarkus.grpc.GrpcService;
import io.quarkus.security.identity.SecurityIdentity;
import io.smallrye.common.annotation.RunOnVirtualThread;
import io.smallrye.mutiny.Uni;
import jakarta.annotation.security.RolesAllowed;
import jakarta.inject.Inject;
import lombok.extern.slf4j.Slf4j;

import java.security.Principal;
import java.util.Base64;

import static com.drive.backend.grpc.security.Role.ADMIN;
import static com.drive.backend.grpc.security.Role.USER;

@GrpcService
@Slf4j
public class FileInfoService implements FileService {


    private final MinioService minioService;
    private final SecurityIdentity identity;

    @Inject
    public FileInfoService(final MinioService minioService, final SecurityIdentity identity) {
        this.minioService = minioService;
        this.identity = identity;
    }

    /**
     * Helper method to safely extract username from SecurityIdentity
     */
    private String getUsername() {
        if (this.identity == null || this.identity.isAnonymous()) {
            log.warn("SecurityIdentity is null or anonymous");
            throw new SecurityException("User not authenticated");
        }

        final Principal principal = this.identity.getPrincipal();
        if (principal == null || principal.getName() == null) {
            log.warn("Principal or principal name is null");
            throw new SecurityException("User principal not available");
        }

        return principal.getName();
    }

    /**
     * This service implements the FileService interface generated by the Mutiny Grpc generator.
     * It provides an implementation for the uploadFile method.
     */
    @RolesAllowed({USER, ADMIN})
    @Override
    @RunOnVirtualThread
    public Uni<io.quarkus.example.FileUploadResponse> uploadFile(final io.quarkus.example.FileUploadRequest request) {
        return Uni.createFrom().item(() -> {
                    try {
                        return this.getUsername();
                    } catch (final Exception e) {
                        log.warn("Authentication failed", e);
                        return null;
                    }
                })
                .onItem().transformToUni(user -> {
                    if (user == null) {
                        return Uni.createFrom().item(io.quarkus.example.FileUploadResponse.newBuilder()
                                .setSuccess(false)
                                .setMessage("User not authenticated")
                                .build());
                    }
                    return this.minioService.uploadFile(Base64.getDecoder().decode(request.getContent()), request.getFilename(), user)
                            .onItem().transform(objectName -> {
                                log.info("File uploaded successfully: {}", objectName);
                                        return io.quarkus.example.FileUploadResponse.newBuilder()
                                                .setSuccess(true)
                                                .setMessage("File uploaded successfully")
                                                .build();
                                    }
                            );
                })
                .onFailure().recoverWithItem(th -> {
                    log.error("Upload failed", th);
                    return io.quarkus.example.FileUploadResponse.newBuilder()
                            .setSuccess(false)
                            .setMessage("Upload failed: " + th.getMessage())
                            .build();
                });
    }

    /**
     * Implementation of the deleteFile method from the FileService interface.
     */
    @RolesAllowed({USER, ADMIN})
    @RunOnVirtualThread
    @Override
    public Uni<io.quarkus.example.FileOperationResponse> deleteFile(final io.quarkus.example.FileDeleteRequest request) {
        final String uuid = request.getUuid();

        return Uni.createFrom().item(this::getUsername)
                .onItem().transformToUni(user ->
                        this.minioService.listUserFiles(user, null, null, null, 1000) // Get all files to find the one with matching UUID
                                .onItem().transformToUni(result -> {
                                    String objectName = null;
                                    for (final FileInfoDto file : result.files()) {
                                        if (uuid.equals(file.uuid())) {
                                            objectName = file.objectName();
                                            break;
                                        }
                                    }
                                    if (objectName == null) {
                                        return Uni.createFrom().item(io.quarkus.example.FileOperationResponse.newBuilder()
                                                .setSuccess(false)
                                                .setMessage("File not found with uuid: " + uuid)
                                                .build());
                                    }
                                    return this.minioService.deleteFile(objectName)
                                            .onItem().transform(success -> io.quarkus.example.FileOperationResponse.newBuilder()
                                                    .setSuccess(success)
                                                    .setMessage(success ? "File deleted successfully" : "Failed to delete file")
                                                    .build());
                                })
                )
                .onFailure().recoverWithItem(th -> {
                    log.error("Delete failed", th);
                    return io.quarkus.example.FileOperationResponse.newBuilder()
                            .setSuccess(false)
                            .setMessage("Delete failed: " + th.getMessage())
                            .build();
                });
    }

    /**
     * Implementation of the renameFile method from the FileService interface.
     */
    @RunOnVirtualThread
    @RolesAllowed({USER, ADMIN})
    @Override
    public Uni<io.quarkus.example.FileOperationResponse> renameFile(final io.quarkus.example.FileRenameRequest request) {
        final String uuid = request.getUuid();
        final String newFilename = request.getNewFilename();

        return Uni.createFrom().item(this::getUsername)
                .onItem().transformToUni(user ->
                        this.minioService.listUserFiles(user, null, null, null, 1000) // Get all files to find the one with matching UUID
                                .onItem().transformToUni(result -> {
                                    String oldObjectName = null;
                                    for (final FileInfoDto file : result.files()) {
                                        if (uuid.equals(file.uuid())) {
                                            oldObjectName = file.objectName();
                                            break;
                                        }
                                    }
                                    if (oldObjectName == null) {
                                        return Uni.createFrom().item(io.quarkus.example.FileOperationResponse.newBuilder()
                                                .setSuccess(false)
                                                .setMessage("File not found with uuid: " + uuid)
                                                .build());
                                    }
                                    return this.minioService.renameFile(oldObjectName, newFilename, user)
                                            .onItem().transform(success -> io.quarkus.example.FileOperationResponse.newBuilder()
                                                    .setSuccess(success)
                                                    .setMessage(success ? "File renamed successfully" : "Failed to rename file")
                                                    .build());
                                })
                )
                .onFailure().recoverWithItem(th -> {
                    log.error("Rename failed", th);
                    return io.quarkus.example.FileOperationResponse.newBuilder()
                            .setSuccess(false)
                            .setMessage("Rename failed: " + th.getMessage())
                            .build();
                });
    }

    /**
     * Implementation of the listUserFiles method from the FileService interface.
     * Lists all files for a specific user from MinIO storage with support for:
     * - Search filtering by filename
     * - File type filtering (all, images, documents)
     * - Cursor-based pagination using UUID
     * - Configurable page limit
     */
    @RunOnVirtualThread
    @RolesAllowed({USER, ADMIN})
    @Override
    public Uni<ListUserFilesResponse> listUserFiles(final ListUserFilesRequest request) {
        return Uni.createFrom().item(this::getUsername)
                .onItem().transformToUni(username -> {
                    // Extract request parameters
                    final String search = request.getSearch();
                    final String filter = request.getFilter();
                    final String lastUuid = request.getLastUuid();
                    final int limit = request.getLimit() > 0 ? request.getLimit() : 20; // Default to 20

                    return this.minioService.listUserFiles(username, lastUuid, search, filter, limit)
                            .onItem().transform(result -> {
                                final ListUserFilesResponse.Builder responseBuilder = ListUserFilesResponse.newBuilder()
                                        .setSuccess(true)
                                        .setMessage("Files retrieved successfully for user: " + username)
                                        .setHasMore(result.hasMore()); // Set the has_more flag

                                // Convert from DTO FileInfo to gRPC FileInfo
                                responseBuilder.addAllFiles(result.files().stream().map(file -> FileInfo.newBuilder()
                                        .setObjectName(file.objectName())
                                        .setFilename(file.filename())
                                        .setSize(file.size())
                                        .setLastModified(file.lastModified().getTime())
                                        .setFileUrl(file.fileUrl())
                                        .setUuid(file.uuid())
                                        .build()).toList());

                                return responseBuilder.build();
                            });
                })
                .onFailure().recoverWithItem(th -> {
                    log.error("List files failed", th);
                    return ListUserFilesResponse.newBuilder()
                            .setSuccess(false)
                            .setMessage("Failed to retrieve files: " + th.getMessage())
                            .setHasMore(false)
                            .build();
                });
    }

    /**
     * Implementation of the getFileCounts method from the FileService interface.
     * Returns statistics about user's files including:
     * - Total number of files
     * - Count of images
     * - Count of documents
     * Supports optional search filtering by filename.
     */
    @RunOnVirtualThread
    @RolesAllowed({USER, ADMIN})
    @Override
    public Uni<io.quarkus.example.GetFileCountsResponse> getFileCounts(final io.quarkus.example.GetFileCountsRequest request) {
        return Uni.createFrom().item(this::getUsername)
                .onItem().transformToUni(username -> {
                    final String search = request.getSearch();

                    return this.minioService.getFileCounts(username, search)
                            .onItem().transform(result ->
                                    io.quarkus.example.GetFileCountsResponse.newBuilder()
                                            .setTotal(result.total())
                                            .setImages(result.images())
                                            .setDocuments(result.documents())
                                            .build()
                            );
                })
                .onFailure().recoverWithItem(th -> {
                    log.error("Get file counts failed", th);
                    return io.quarkus.example.GetFileCountsResponse.newBuilder()
                            .setTotal(0)
                            .setImages(0)
                            .setDocuments(0)
                            .build();
                });
    }
}